### PR TITLE
Re order dockerfile for yarn

### PR DESCRIPTION
**Pull request by mkrowe**
If the files (perhaps only package-lock.json ?) aren't copied into the container before `yarn install` is run, then the assets aren't correctly copied.

This gets picked up locally when yarn install is executed a second time as part of assets:precompile, but there are some conditions (AWS Codebuild, DIND) that mean it doesn't find any changes.

By moving the `COPY . .` command before the bundle and yarn commands, everything works in both scenarios.

### CODE REVIEW

**Comment by floehopper** [comment]
The failing Travis CI build for this PR should be fixed by rebasing against the latest `master`.

**Comment by mkrowe** [comment]
Will rebase against add-dockerfile branch once that's been updated from master (unless these changes are incorporated beforehand, in which case this PR can just be closed).

**Comment by mkrowe** [comment]
Closed, as changes incorporated into #1

**Comment by chrisroos** [comment]
Thanks, @mkrowe :-)

**Pull request closed without merging**
