### PR TITLE
WIP: Download supplier list

### PR DESCRIPTION
**Pull request by chrislo**
Still to do: 

- [ ] Implement download button as per [this codepen](https://codepen.io/anon/pen/xydwer) 
- [ ] Add spreadsheet generation logic to Branch
- [ ] Fix feature tests using a library that supports spreadsheet *reading*
- [ ] Squash or ignore ruby warnings that are generated when running the specs
- [x] Remove c8fdc84 (print link to be added in a different story)

### CODE REVIEW

**Comment by floehopper** [comment]
@chrislo @techbelly:

It looks as if the [axlsx_rails][1] gem provides a renderer and a template handler for [axlsx][2].

Also if we want to read (as well as write), it might be worth considering [rubyXL][3] instead of axlsx as long as it can write the formula we need. As far as I can see axlsx is not capable of reading.

[roo][4] which I think Ben has been using is another option which can do both reading & writing.

[This blog post][5] provides a useful review of a bunch of libraries.

[1]: https://github.com/straydogstudio/axlsx_rails
[2]: https://github.com/randym/axlsx
[3]: https://github.com/weshatheleopard/rubyXL
[4]: https://github.com/roo-rb/roo
[5]: https://spin.atomicobject.com/2017/03/22/parsing-excel-files-ruby/

**Comment by chrislo** [comment]
While investigating yesterday I tried the `axlsx-rails` gem and the `roo` library and both had issues (mostly deprecation warnings) with the version of ruby and rails we are using. `rubyXl` looks interesting - I hadn't seen that one.

**Comment by techbelly** [comment]
Cherry-picked out the "Print this page" commit and rebased this branch against master, force-pushing. @chrislo

**Comment by chrislo** [comment]
Thanks for your help with this. A re-worked version of this PR was added in 2391133 and related neighbouring commits.

**Pull request closed without merging**
