### PR TITLE
WIP: Introduce Journey#previous_questions_and_answers

### PR DESCRIPTION
**Pull request by chrisroos**
So that we can avoid having to explicitly list the fields to ignore.

Unfortunately this doesn't yet work. There's a problem with (at least) the
`SchoolPostcode` step in that it defines `worker_type` as an attribute,
even though `worker_type` comes from the previous `WorkerType` step. I
wonder whether it'd be useful to differentiate between the attributes
we're going to ask the user to enter, and those that come from previous
steps?

I've made Journey#params a HashWithIndifferentAccess so that I can
slightly simplify the implementation of
`previous_questions_and_answers`. The `params` contain keys as strings
while the `#attributes` method returns an array of symbols.

### CODE REVIEW

**Comment by chrisroos** [comment]
@techbelly, @chrislo, @floehopper and @threedaymonk - Do any of you have any thoughts about how I might implement `Journey#previous_questions_and_answers`? I was hoping I could use the `attribute`s defined in the steps to represent the questions we ask users for that step. Unfortunately, we also use `attribute`s to collect information submitted in previous steps (e.g. the `worker_type` attribute in `SchoolPostcode`).

**Comment by threedaymonk** [comment]
The `worker_type` is only needed, I think, because there are multiple paths to that node. If we had different steps for _postcode for nominated_ and _postcode for agency supplied_, then each step would only need its own attributes. I think the duplication might be worth the conceptual simplification.

**Comment by chrisroos** [comment]
Thanks @threedaymonk - I'll take a look to see whether introducing two steps helps.

**Comment by chrisroos** [comment]
Hey @threedaymonk - What do you think about the changes in https://github.com/Crown-Commercial-Service/crown-marketplace/pull/25/commits/deb2098059204daccc1c1799e21219e90bdb324c which splits the `SchoolPostcode` step into two? I quite like it because it means that  `Journey#previous_questions_and_answers` now works as expected. If you think it looks OK then I'll reorder these commits so that I split the SchoolPostcode step first.

**Comment by threedaymonk** [comment]
This all seems great. It's simpler to use when adding new steps, and the oddity of the postcode step is gone. I think the slightly less terse paths are worth it.

**Comment by chrisroos** [comment]
Great!. Thanks @threedaymonk. I'll get the commits tidied and merged.

**Comment by chrisroos** [comment]
I've manually merged these changes into master so I'm closing this PR.

**Pull request closed without merging**
