### PR TITLE
Feature/st 69 admin tool

### PR DESCRIPTION
**Pull request by iceraluk**
1. ST-69 Supplier Data Admin Tool design - wireframe/prototype
- setup all the different screens
- moved data generation script to the lib folder
- added validations
- implemented state machine
- added tests

2. ST-81 Admin tool: Add file type and file size validations on upload
3. ST-79 Move data generation script to a background job

### CODE REVIEW

**Comment by tariqhamid** [comment]
Are you really using Sinatra with Rails ?

**Comment by iceraluk** [comment]
> Are you really using Sinatra with Rails ?
> 
> If not please remove it.
> 
> We want to keep gem usage low ;)

Sinatra is a dependancy of Sidekiq ( mounts inside the rails app for the sidekiq Web UI)

**Comment by tariqhamid** [comment]
I see. I guess that depends on Slim as well.

**Comment by iceraluk** [comment]
> I see. I guess that depends on Slim as well.

yep

**Comment by tariqhamid** [comment]
I am concerned that 
lib/tasks/supply_teachers/scripts/bootstrap_supplier_lookup.rb
holds actual supplier data

That can be held externally? Maybe on an s3 bucket.

**Comment by iceraluk** [comment]
> I am concerned that
> lib/tasks/supply_teachers/scripts/bootstrap_supplier_lookup.rb
> holds actual supplier data
> 
> That can be held externally? Maybe on an s3 bucket.

**Comment by iceraluk** [comment]
> I am concerned that
> lib/tasks/supply_teachers/scripts/bootstrap_supplier_lookup.rb
> holds actual supplier data
> 
> That can be held externally? Maybe on an s3 bucket.

It's not sensitive data. But it's not needed in there so I have removed the hardcoded supplier names from the script

**Comment by iceraluk** [comment]
Best place to store secret keys is environment variables (for localhost use .env.local)

**Pull request merged**
